language: node_js
node_js:
- node
before_script:
- npm i -g gatsby
- npm i
script:
- npm run build
deploy:
  provider: s3
  secret_access_key:
    secure: rpq0knMa2pzL+v6ym6Sh7U+aT2L6+gxXThJCvXW/c82bn1CL9op2l6AB3sJejc5yIa1AWEUfZoUGAhehEaj3VoS7KQ01YySyPPxPrvQelASvuWi4Lgf0mIeMmGSsivFvThQ0l5vsQ32vpkdFnSFbw7/wuTAjc6syLYD5GtEk5u5SA5nULq04u3aqMqv96z5m5c6ob191FE0zp9LaKIStn/91LYfMPkGbuymhuDP5QhzaMUwj4ah7/NKxr5aqR/bSDKQFkpj4IwXBxWUyzLbbV3jlQXPT4iYAf7jH6VMxwvDKPmwo5TgtwOeOjpCCR6O0drNNH47gByI6FDLA4XFRZ/j16+iDdULnucvxhWt3TwSzat8ypOt7nSvrRzGCtsuM+9r8MSRe+IFltHGYoO0rfiSYx0VCiKggfue020VSP7BqFa6u2PMPMalja0v0bBGv5IR3351bhA3cWSbWYalaRI8UUedovi6snICkKlJWLv1t0ER2rYYkgQAO0dUk/d/b9UoqKiGtQeMQ54lUic/VymDQPHO7zZfRADf0SSU8YVtO+TQsw17PgG6nPf0VNx33xov4q5l5btQtKQH3lqSEFyz7ynGCT3FvOWuvauSTfBxHfAEO0fIPlPqYQ9zG8cQPKUL22pbOt6t64tD6VDr0LEvxpq9PXXq8a6Z5qlGA2h4=
  bucket: cameronstinson.cool
  local-dir: public
  acl: public_read
  on:
    repo: cameronstinson4/multi-cloud-index
