language: node_js
node_js:
- node
before_script:
- npm i -g gatsby
- npm i
script:
- npm run build
deploy:
  provider: s3
  access_key_id: 
    secure: "Mrem3DMYhRpMqIXi8WyyZKEujZgJ6wqX34k6Osm5zMWAq0R4yNDxlzR2anbcNggLr19JYGKL6odbYnceUrvp4l3Vbo6Uet6TD2FWeuOAMSbnJzE01iHC/1Q49y8H5f4NEzoITI2WmnSPJ6obLWPoSDPZUQbN9Cw1uG0dPpnY7M3g+4SwQL+0HxQHH1i18CZzCQCF4dFH8t67GG1GyDXZA8m/g4v7huRmpyQF0JSjmahaZrO4w/tqinPc7VTj7zNUZpqYWgH7Quyt8FM2ibQLQMyMKP5aZaWitNjfwVtgsh64PGpOl267WnvC7Bnz76wCJD8z7yqud1ozmil4cHaVWowX8jEgjydvRQQp8c13xY0K3aWZRK4BQqxUz4TGd2ybXkFObRQ/elG6/Y+P5DoGkBfasWGBxegqBlu9T+eT4L/7i9tc6BQFaf2UEGfMHteXLYYgZNo/5XVefyuK2KEaM1h7+eEIlyKMnDVpV/0JVx4SHBPZ0UOXHgabTY7dYV8jI6OO6MaDzk0aJbnTRRW8OYc7xs+RnUWHWxJpbH/DGF8e4e5u5o/mPX1EVW5SrffnQI7coQJmZMNft8gog+27vpjyt2tVUyjRcPuAofpRro6ybfjM3uXPlG5uO1MYYIgZ6MTxek+djFtFycUUg/OwwcUKR2d9hsmkZy3ISadnQPY="
  secret_access_key:
    secure: "lLzUhxo3CqRaQhAqofuskTGgAeDglXop45CrOicyUzYZ9RJvFyyb9PiRJ4dE1ilkBJDbCZUifHyXuC3mLKGnydmdM5cGGNvIpz/Oq1130kJASzp0cg6u/tpbm0w6wOBWskmlw8Bo/lke+SklcuipQ8I2+10kFR05JLTCrD2Nxv3pQYKxfA5/7byVq66SkSmBmIoLa1PMU1Yxj43JabMvlkxDd0RDbgMgFMLsGQ9WGc/21s7FOtaMO/MtAC+Ily9/wRVcOid3EKA4lmipurB3MbHTINJn8+v1Vsy3HUu7eDPRU8dbxdYFFrzbmEJwws4uO0kRV3NhpoMytLBX13Hh79ymB6jvi0CoIFntHKozmYxUdFehDb7bNVdjeohMhal/x3svOBCfa2Wop5n391RONQgvx7ash5ySy8x6RqTLSq3yd7Ob6QG8OhGiH4LmHxSDsyNF/M0x5AVA/vBzaxOdjGHpug2O1UGEfZlLBTvkr6hfv/caFdOiuwc9MmeG8OFmHFKjgr9dTcV83+oGgicr6Gm4DdllMjAa5bvnYiQkX6MH9JCK8PE6WyhegTtvWkjOi2fVBYw+fPAZ5bwK6ALWBjImVMuTKWphd7FS6I0dnng52ilA7o3QBsNllY0SLMflqiKdssDaRmQqbe1t+zkSHr3gjRdyU1xaVMHsrGPnVM0="  
  bucket: cameronstinson.cool
  local-dir: public
  acl: public_read
  skip_cleanup: true
