  
language: node_js
node_js:
  - node
deploy:
  provider: s3
  access_key_id:
    secure: "oqp38e0Vip9scMBrb9moeIBHwOj4FNkRd8Loyzwk47+lUqZAaFImrzLHpyyWzUHmFLee8/MRtd0nN5T+7vuYmg+Ox2GbaouQiUQvR24meuE/Zt6VGU84LDEtq7NvF1LuXtoF2Qqp/+YhAmoHksQoJ5cZ6zwhgrv+0MVN2rCjngbTSNnXl7xeKqqmlznv8AFcEpVwo4klVwBhTS5aLXLYws7FAp4mqr4GZ5OfyztosAplnzXJVvIF4z7iuUZKrK84fI/qi8PIVWx3Ou8QxcJeMqax/fjkwkO8IsMWnfGFSTshSd2VBtps+Qlq7ymNgRmc2QCCW7BevynuYjqfgbIO8bkDShjaD9KFEgLMlgMSwGcOdUbXfFksKcjWq3UoFagC0ZLCxM5q8X4ewnMOrxV31c860EenJZ2Heqflx1/AC6uq3EL9JdkWLVj3NfN7+qK/Xp+VBc1MhS7QwdfGHpwajI95bQvFHbq31K/Gka83bqfY1B/U/4GNurhxrJfo31eWS0m48gdjYF6sJc+0AnmJkTlt0zrezb50zdPWJi2HM4Xm4UtE3uuGRM29JdOmQ/k4i4tvH6CLaxB42hNhUO++HjQBtA/+yosSwHsCtaiBdrGUAQ6hQVp3qgWM8U6JR1j56BQf77ABh8T9i7caqirOjK/M3L27I7t82Jux9SNkGgs="
  secret_access_key:
    secure: "kyBWTThfAFaca+fngEGhe/GwM9N9yYdMXZezVdiKUoiGD9EHztdi6+VtNt+Bl87r+hhopJ3aXJFwp3Kw7WN7p19pa1hB/gMG+snJVH2TDp5owrvCT+2d+15n4bbsi6XFgsixIgSLgmAySilcOrIdvENlaFp7vg/oLWlvcVhm37SdqYQpfe1rWV9q5mXD5uxxHQFgbm6efduhNjPhtOwDqNT8aapz0EbuFHxJ+S/CDH5X2EvCUP5lfPSbMy17/OuBbZnFg22xC9/4a7ULMK+G4aOZWjpuPPi1n52K4EHCMeMFoH6Etd2DeY8ys5gcLAceZEo218seU/AWvEEUztZpq8yQLXLdDhp8SfWNIHmKt6W1FYgykL9EKM/OmXpSGKMYvTUlWvtOvPjTfSKfJUOqEkg/rbNiDTCBpQQiswLUTjaG62dW1UqrDkLOTZ1+nwCIf4TniMNl1SdofZHBB2PdC8x58Lb82n0wZDX3xcieVrjhyr/1URC1juq5zihFF6l6kmWSd+Mybjb7lhHqzwbpRQR1KB2GiPSXqjPXGlgw4fVIaMq3jq/3D11TdXnyFa923pb1Aef7naDrMVSnVbUxIxvwIgOfk5x4akQplCpKcrJmH+UyB/+FR07z12iSXFmlJavfTuAkOfUwugSrXT+OYxk74tOQpImOL61XIDXOHhA="
  bucket: "cameronstinson.cool"
  acl: public_read
  skip_cleanup: true
  region: us-east-1



before_script:
  - "npm i -g gatsby"
  - "npm i"

script:
  - "npm run build"